### ISSUE TITLE
Error when parent commit not found

### ISSUE THREAD

**Issue by davidferlay** [skilld-labs/plasmactl-bump#30]
## Observed

- Following https://github.com/skilld-labs/plasmactl-bump/issues/10, bump now checks for all commits untill previous bump commit and changes the version of all resources modified in those commits
-  To do so, code seem to get parent of commits
- However there are some case where parent commit of one commit does not exist anymore (most likely because of rewritten history)
- When that happens, core returns an error and exits

```
Bump updated versions...                              
List of unversioned files:
README.md
README.svg

Error: commit parent not found
```

## Expected

- It's not clear why looking for parents of commits is required in bump logic
- Let's look for a way to iterate on commits without getting their parent

**Comment by DeNevero** [comment]
https://github.com/skilld-labs/plasmactl-bump/pull/31
